### ISSUE TITLE
[JOSS-REVIEW] autostreamtree install fails due to pysam

### ISSUE THREAD

**Issue by abhishektiwari** [tkchafin/autostreamtree#7]
Running in Docker container

```
docker run -it --rm condaforge/miniforge3
```

Followed installation instructions,
```
(streamtree) root@79da57b9716d:/# mamba install -c ecoevoinfo -c conda-forge -c bioconda autostreamtree

Looking for: ['autostreamtree']

ecoevoinfo/linux-aarch64 (check zst)                Checked  0.2s
ecoevoinfo/noarch (check zst)                       Checked  0.1s
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
bioconda/linux-aarch64 (check zst)                  Checked  0.1s
bioconda/noarch (check zst)                         Checked  0.2s
ecoevoinfo/linux-aarch64                           125.0 B @   1.3kB/s  0.1s
bioconda/linux-aarch64                             854.0 B @   5.7kB/s  0.2s
ecoevoinfo/noarch                                    1.4kB @   7.1kB/s  0.2s
conda-forge/noarch                                  13.3MB @  27.5MB/s  0.5s
conda-forge/linux-aarch64                           10.2MB @  16.0MB/s  0.7s
bioconda/noarch                                      5.1MB @   4.6MB/s  1.0s

Pinned packages:
  - python 3.10.*


Could not solve for environment specs
The following package could not be installed
└─ autostreamtree is not installable because it requires
   └─ pysam, which does not exist (perhaps a missing channel).
```

**Update**
- Install pysam via pip but still failing to install autostreamtree

```
conda install pip
pip install pysam
```

[JOSS-REVIEW](https://github.com/openjournals/joss-reviews/issues/6160)

**Comment by tkchafin** [comment]
Hi @abhishektiwari, thanks for documenting the issue. It looks like pysam doesn't have a conda installation for linux-aarch64 (only for linux-64). I'll look into today if I can build an alternate distribution for pysam that will fix the problem.

**Comment by tkchafin** [comment]
So I looked into it, and there are a lot of compiled dependencies for pysam which also won't support ARM, so fixing that issue just results in more errors. Using an ARM linux you will need to use a workaround as for ARM Macs. In this case you should just be able to add `--platform linux/amd64` to your docker call:
```docker run -it --rm --platform linux/amd64```

This should make it installable for you. I'll go ahead and put a docker image together for this as well, and update the documentation once published

**Comment by tkchafin** [comment]
I added pre-built Docker images you can access like:
```
docker run -it tkchafin/autostreamtree:latest
```

Also added this to the documentation, and the CI/CD workflows will now build and upload to conda and docker on each new release. Let me know if you encounter any further issues, but this is all working on my end so I'll close for now

**Comment by abhishektiwari** [comment]
Fantastic let me give a try. Should be good now. Feel free to close it for now.
